### ISSUE TITLE
Undefined reference to inlined function db_reconnect() in addrwatch_mysql.c

### ISSUE THREAD

**Issue by lynnewu** [fln/addrwatch#11]
in addrwatch_mysql.c, the function db_reconnnect() is defined as "inline void", which results in this error:

undefined reference to `db_reconnect'

Removing "inline" lets it build correctly.  May be due to changes in how gcc handles inline declarations?  Documentation for gcc seems to indicate that it will inline small functions automatically.

gcc:  gcc (Debian 7.3.0-5) 7.3.0
OS:  4.14.0-kali3-amd64 #1 SMP Debian 4.14.17-1kali1 (2018-02-16) x86_64 GNU/Linux

**Comment by fln** [comment]
Thanks for reporting the issue, fix is in the master branch now.
