### ISSUE TITLE
Configure Error

### ISSUE THREAD

**Issue by samoehlert** [fln/addrwatch#3]
I am having an issue trying to configure this (Does this work on Centos?).

```
[root@test ~]# cat /etc/redhat-release
CentOS release 6.5 (Final)
[root@test ~]# rpm -q libevent
libevent-1.4.13-4.el6.x86_64
[root@test ~]# rpm -q libpcap
libpcap-1.4.0-4.20130826git2dbcaa1.el6.x86_64
```
It would appear I have all necessary prerequisites. On trying to configure though:

```
[root@test addrwatch]# ./configure
./configure: line 2252: syntax error near unexpected token `-Wall'
./configure: line 2252: `AM_INIT_AUTOMAKE(-Wall foreign check-news silent-rules -Werror)'
```

**Comment by fln** [comment]
Hi, I have tested addrwatch with CentOS 6.7 and it works fine. However building toolchain requires an autoconf that is newer than version currently shipped with Centos 6.7.

I have prepared a distribution package at https://github.com/fln/addrwatch/releases/download/0.8/addrwatch-0.8-master.tar.gz which contains a configure script generated with the newer autotools. It is tested on CentOS 6.7 but I think it should also work on CentOS 6.5.

If you need a distribution package for shared-memory addrwatch version please let me know.
