### ISSUE TITLE
man page differs from help output / available options

### ISSUE THREAD

**Issue by acobaugh** [fln/addrwatch#8]
In particular, -l/--syslog does not seem to work, but is mentioned in the man page.

**Comment by q2dg** [comment]
Well, a so simple change and it's not taking into account still two years after...
It seems this project is pretty abandoned

**Comment by fln** [comment]
Pull requests are more than welcome. Syslog flag was available in pre v1.0 releases. Since v1.0 is replaced by separate addrwatch_syslog tool.
